#!/bin/bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."
GIT_ROOT=$(git rev-parse --show-toplevel)
cd $GIT_ROOT
results=( $(find $GIT_ROOT -path "*/bin/activate") )
if (( ${#results[@]} )) ; then
    echo "Virtual environment found"
else
    echo "No virtual environment was found"
    echo "==> Installing virtualenv dependencies…"
    pip3 install virtualenv
    python3 -m venv env
fi

echo "==> Activate Virtual Environment…"
source "${results[0]}"
echo "==> Installing package dependencies…"
pip install -e .
