#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

git submodule update --init --recursive

script/bootstrap

echo "==> Package is now ready to go!"
echo "==> Do not forget to activate the virtual environment!"
