#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ENV_BINS=$SCRIPT_DIR"/../env/bin/"
TEST_DIR=$SCRIPT_DIR"/../tests/*"
source $ENV_BINS"activate"
cd $ENV_BINS
coverage run -m pytest $TEST_DIR
coverage report -m
