name: CodeCov

on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: "3.10"
    - name: Generate Report
      run: |
        sudo apt update && sudo apt install dvipng ghostscript texlive-fonts-recommended texlive-base texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-publishers texlive-science texlive-xetex cm-super
        pip install -e .
        pip install pytest
        pip install coverage
        coverage run -m pytest ./tests/*
        coverage report -m 
        coverage json 
        # pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        env_vars: OS,PYTHON
        fail_ci_if_error: false
        flags: unittests
        name: codecov-umbrella
        verbose: true
